version: '3'


services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
    container_name: db

  backend:
    image: asifpracticum/food_backend_final:latest
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    container_name: backend

  frontend:
    image: asifpracticum/food_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
    container_name: frontend

  nginx:
    image: asifpracticum/food_nginx_final:latest
    ports:
      - "9000:80"
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - backend
    restart: always
    container_name: nginx

volumes:
  static:
  media:
  postgres_data: